# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    conf.path: "%kernel.root_dir%/appConfig"
    repo.path: "%kernel.root_dir%/../var/repo"
    build.context.path: "%kernel.root_dir%/docker"
    build.registry.url: "172.29.134.38:5000"

services:
    app.config.manager:
        class: AppBundle\Service\AppConfigManager
        arguments: ["%conf.path%", "@filesystem"]

    docker:
        class: Docker\Docker

    app.builder:
        class: AppBundle\Service\BuildManager
        arguments:
            - "@docker"
            - "@filesystem"
            - "%repo.path%"
            - "@app.config.manager"
            - "%build.registry.url%"
            #- "%build.context.path%"

    app.project.repository:
        class: AppBundle\Service\ProjectRepository
        arguments: ["%repo.path%", "@filesystem"]

    form.app.data.image:
        class: AppBundle\Form\AppDataBuildConfType
        arguments: ["@app.config.manager"]
        tags: [ name: form.type ]

    form.cron.image:
        class: AppBundle\Form\CronBuildConfType
        arguments: ["@app.config.manager"]
        tags: [ name: form.type ]

    form.logrotate.image:
        class: AppBundle\Form\LogrotateBuildConfType
        arguments: ["@app.config.manager"]
        tags: [ name: form.type ]

    form.project.related.image:
        class: AppBundle\Form\LogDataBuildConfType
        arguments: ["@app.config.manager"]
        tags: [ name: form.type ]

    form.pr.with.conf.image:
        class: AppBundle\Form\PRWithConfigBuildConfType
        arguments: ["@app.config.manager"]
        tags: [ name: form.type ]

    form.sub.linked.project.env:
        class: AppBundle\Form\LinkedProjectEnvSubType
        arguments: ["@app.config.manager"]
        tags: [ name: form.type ]

    form.sub.linked.config:
        class: AppBundle\Form\LinkedConfigSubType
        arguments: ["@app.config.manager"]
        tags: [ name: form.type ]